// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadProbes returns the embedded CollectionSpec for probes.
func loadProbes() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProbesBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load probes: %w", err)
	}

	return spec, err
}

// loadProbesObjects loads probes and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*probesObjects
//	*probesPrograms
//	*probesMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProbesObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProbes()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// probesSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probesSpecs struct {
	probesProgramSpecs
	probesMapSpecs
	probesVariableSpecs
}

// probesProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probesProgramSpecs struct {
	ProbeCryptoCall *ebpf.ProgramSpec `ebpf:"probe_crypto_call"`
}

// probesMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probesMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// probesVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probesVariableSpecs struct {
}

// probesObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type probesObjects struct {
	probesPrograms
	probesMaps
	probesVariables
}

func (o *probesObjects) Close() error {
	return _ProbesClose(
		&o.probesPrograms,
		&o.probesMaps,
	)
}

// probesMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type probesMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *probesMaps) Close() error {
	return _ProbesClose(
		m.Events,
	)
}

// probesVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type probesVariables struct {
}

// probesPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type probesPrograms struct {
	ProbeCryptoCall *ebpf.Program `ebpf:"probe_crypto_call"`
}

func (p *probesPrograms) Close() error {
	return _ProbesClose(
		p.ProbeCryptoCall,
	)
}

func _ProbesClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed probes_bpfeb.o
var _ProbesBytes []byte
